### ISSUE TITLE
Gradle dependency

### ISSUE THREAD

**Issue by qcfer35** [navasmdc/MaterialDesignLibrary#1]
Hey, you do not have this project in maven?

**Comment by romangromov** [comment]
Hi guys,

how is this task going on?

**Comment by TriPSs** [comment]
I'm using it now for a while and i can really recommend to include the project to your own app, because then you can still change little things like the ripple speed.

**Comment by qcfer35** [comment]
@TriPSs 
I think the library is not 100%, these details should be supporter of the library without making changes, however there must be reliance on Gradle to use and detect errors

**Comment by navasmdc** [comment]
Hi guys, GOOD NEWS!!, I've finally gotten it, I've upload the project to the Jcenter if you want acces to the library, have to add these lines in your buil.gradle

repositories {
    jcenter()
}

dependencies {
    compile(group: 'com.github.navasmdc', name: 'MaterialDesign', version: '1.0', ext: 'aar')
}

**Comment by romaloma** [comment]
Not working again.... Error:(25, 13) Failed to resolve: com.github.navasmdc:MaterialDesign:1.0

tried with both

**Comment by navasmdc** [comment]
Hi, the library is in the 1.4 version try with this compile line

compile 'com.github.navasmdc:MaterialDesign:1.4@aar'
