### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by biaomingzhong** [navasmdc/MaterialDesignLibrary#100]
`java.lang.NoClassDefFoundError: com.nineoldandroids.view.ViewHelper `

I'am using android studio.I can use  the com.gc.materialdesign.views.ButtonRectangle.But I can not use the ButtonFloat.

`compile 'com.github.navasmdc:MaterialDesign:1.+@aar'`

**Comment by biaomingzhong** [comment]
Sorry to borther you. I solve the problem after adding the nineoldandroids jar.Thank you for your sharing !

**Comment by moslem-pc** [comment]
i have the exact same problem!
where should i add it????

**Comment by moslem-pc** [comment]
oh sorry friends!
problem wasnt about the files!
i needed to add:
compile 'com.nineoldandroids:library:2.4.+'
to dependencies in gradle.build
