### ISSUE TITLE
set font to ButtonRectangle View 

### ISSUE THREAD

**Issue by S-Masoud-Emamian** [navasmdc/MaterialDesignLibrary#103]
I am using MaterialDesignLibrary. now, I would like to set my font to ButtonRectangle View. how can I do ?

        <com.gc.materialdesign.views.ButtonRectangle
            android:id="@+id/my_btn"
            android:layout_width="wrap_content"
            android:layout_height="40dp"
            android:background="@color/color_default_buy_a_item"                    
            android:text="my btn"
             />

my_btn.setTypeface(font);

    The method setTypeface(Typeface) is undefined for the type ButtonRectangle

**Comment by Inoy1st** [comment]
@S-Masoud-Emamian 
Are you using Android Studio?
You have working app and this is the only thing that is bothering you?

**Comment by S-Masoud-Emamian** [comment]
I'm using eclipse and until now I haven't any problem but changing font.

**Comment by Inoy1st** [comment]
@S-Masoud-Emamian 
Thanks for fast reply!
Are you using latest Library version?

**Comment by S-Masoud-Emamian** [comment]
yes. it works fine to me.
