### ISSUE TITLE
Set flat button typeface/textStyle

### ISSUE THREAD

**Issue by vipulyaara** [navasmdc/MaterialDesignLibrary#112]
There is no option (as far as I could find) to change the typeface or textStyle of flatButton. I want a button WITHOUT bold typeface. Is there a way to achieve this? (Letting us use "android:fontFamily" attribute on buttons would be nice)

**Comment by navasmdc** [comment]
Hi friend, if you want change the typeface of the ButtonFlat you could call the getTextView() function to get his TextView, and with this textview you can change his typeface

**Comment by vipulyaara** [comment]
Thank you so much. And thanks for an awesome library :)
