### ISSUE TITLE
Ripple effect animation speed

### ISSUE THREAD

**Issue by Ishwor-Shrestha** [navasmdc/MaterialDesignLibrary#116]
I was wondering if there is any way to change the ripple effect speed in LayoutRipple. Is there any documentation for this project?

**Comment by rpdave** [comment]
To change the speed of the ripple you can go to line number 55 in ButtonFloat.java
and edit this line:
rippleSpeed = Utils.dpToPx(2, getResources());

change the 2 to a larger number and you will see the effect speed up =)

**Comment by Ishwor-Shrestha** [comment]
Thanks for the help rpdave

**Comment by maxglu** [comment]
This is possible via xml?
