### ISSUE TITLE
TextSize for Buttons

### ISSUE THREAD

**Issue by borgwald** [navasmdc/MaterialDesignLibrary#121]
textSize-Attribute in XML is ignored. How to set textSize for Buttons? Seems it is not implemented.

**Comment by borgwald** [comment]
solved. 

String x = attrs.getAttributeValue(ANDROIDXML, "textSize");
            int type;
            type = TypedValue.COMPLEX_UNIT_SP;
            x = x.substring(0, x.length()-2);
            textButton.setTextSize(type, Float.parseFloat(x));

**Comment by patelakshay13890** [comment]
But how can I set textSize property in the XML itself not dynamically like android:textAppearance="?android:attr/textAppearanceLarge" ?

**Comment by patelakshay13890** [comment]
?????
