### ISSUE TITLE
Read wrong attribues value for click after ripple

### ISSUE THREAD

**Issue by Robertoq7** [navasmdc/MaterialDesignLibrary#126]
Hi,

In the Button.java class you set this in the consturctor:
`"clickAfterRipple = attrs.getAttributeBooleanValue(MATERIALDESIGNXML,"animate", true);"`

instead of  this (from attrs.xml):
`<!-- if true, delays calls to OnClickListeners until ripple effect ends -->`
`<attr name="clickAfterRipple" format="boolean" />`

Thanks,
Robert

**Comment by navasmdc** [comment]
Ohh, Thanks, I did't have seen the error, I'm going to fix it

**Comment by drinfernoo** [comment]
Was this ever actually fixed? The issue got closed, but the code hasn't changed, and the attributes still aren't working correctly.
