### ISSUE TITLE
setCanceledOnTouchOutside(false)  not work

### ISSUE THREAD

**Issue by HsingPeng** [navasmdc/MaterialDesignLibrary#129]
dialog = new Dialog(this,getString(R.string.connect_error),data);
dialog.setCanceledOnTouchOutside(false) ;
dialog.setCancelable(false);
dialog.show();

setCanceledOnTouchOutside(false)  not work
setCancelable(false)  is OK .

thanks.

**Comment by TurKurT656** [comment]
this is because the method has set to true value. and its a bug

**Comment by HsingPeng** [comment]
Thank you.
I override Dialog.class .
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        RelativeLayout backView = (RelativeLayout) findViewById(R.id.dialog_rootView);
        backView.setOnTouchListener(new View.OnTouchListener() {

            @Override
            public boolean onTouch(View v, MotionEvent event) {
                return false;
            }
        });
    }

Then it works .
