### ISSUE TITLE
there is a white line at the SnackBar bottom

### ISSUE THREAD

**Issue by HsingPeng** [navasmdc/MaterialDesignLibrary#130]
The following photo shows that
![Image](http://ww4.sinaimg.cn/large/005yyi5Jjw1eooay44guej30f80nhtan.jpg)

code:
new MySnackBar(this,intent.getStringExtra(Config.TASK_DATA)).show();

Thanks
Your widgets are awesome !

**Comment by navasmdc** [comment]
Hi, sorry but I don't know what is that line, I use the SnackBar in some applications and that line never has appeared .

**Comment by jaydeep17** [comment]
Same problem here.
That line appears because the snackbar is a little above the controls. Thus there's a little gap between the lower controls and the snackbar.
