### ISSUE TITLE
change animation time for button

### ISSUE THREAD

**Issue by abhi9** [navasmdc/MaterialDesignLibrary#142]
The action under onClickListener can only be triggered after ripple effect finished. So, I would like to change animation time because its very slow in some devices thanks.

**Comment by ArtemMikhaylov** [comment]
I just did it.  But you will need to add materialDesignLibrary as project library.  Then find class com.gc.materialdesign.views.ButtonFloat. In this class find method: "setDefaultProperties()".  And then change default value:

**Comment by Joxad** [comment]
Thanks for the advice, the best would be to put these in attr.xml :+1: 
But it s really nice already!

**Comment by vgravariya** [comment]
xml attribute  materialdesign:rippleSpeed="100" works for me

**Comment by reidsheppard** [comment]
How do you set that value from a style.xml so that I can apply the same value across all my buttons?

**Comment by ankitp94** [comment]
How to know the expected time of ripple animation programmatically, so that it can be changed?
It was working fine for few Android mobiles but was drastically slow on a few.(irrelevant of Android version)

**Comment by sohayb** [comment]
Please close this issue, as it's solved already.

**Comment by lricardo** [comment]
One more thing: there are two namespaces called materialdesign and only one of them works. I added xmlns:materialdesign="http://schemas.android.com/apk/res-auto" and the xml attribute materialdesign:rippleSpeed="100" and it did the trick!

**Comment by boggogo** [comment]
How exactly did you add the project as a library ArtemMikhaylov? I get "Error:Configuration with name 'default' not found." error :/

**Comment by ArtemMikhaylov** [comment]
@boggogo there above lricardo texts, that materialdesign:rippleSpeed="100" works. Maybe I just didn't try so big value for this attribute.   

As I remember, I added this library as usual:
1) download zip  and place library folder to your project folder (one level with app folder)
2) in your app gradle file  in dependencies block:
```groovy
compile project(':materialdisign')
```
I don't remember now, if there was some issues, or wasn't

**Comment by boggogo** [comment]
Thank you for your reply @ArtemMikhaylov . Since I could not include the project as a library I ended up using different animation. :)

**Comment by djokobozinov** [comment]
@vgravariya thanks, good answer
