### ISSUE TITLE
Ripple problem in list view

### ISSUE THREAD

**Issue by dibakarece** [navasmdc/MaterialDesignLibrary#145]
![device-2015-02-06-130459](https://cloud.githubusercontent.com/assets/10453203/6075864/c49c9e2a-ae00-11e4-8e81-e9e09b3c1058.png)
I'm using your ripple view in my demo project.I'm using a list view in slide panel and each item in list view is extend by ripple view.But when i'm scrolling my list it spotted a bubble in list item.

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:materialdesign="http://schemas.android.com/apk/res-auto"
    android:layout_width="fill_parent"
    android:layout_height="wrap_content"
    android:background="@android:color/transparent"
    android:orientation="horizontal" >

```
<com.gc.materialdesign.views.LayoutRipple
    android:id="@+id/itemButtons"
    android:layout_width="fill_parent"
    android:layout_height="wrap_content"
    android:background="#FFF"
    android:clickable="true"
    android:paddingBottom="10dp"
    android:paddingTop="10dp" >

    <ImageView
        android:id="@+id/rowIcon"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:paddingLeft="16dp"
        android:src="@drawable/ic_launcher" />

    <TextView
        android:id="@+id/rowText"
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center_vertical|left"
        android:layout_toRightOf="@+id/rowIcon"
        android:paddingLeft="12dp"
        android:text=""
        android:textAppearance="?android:attr/textAppearanceMedium"
        android:textColor="#4c4c4c"
        android:textStyle="bold" />
</com.gc.materialdesign.views.LayoutRipple>
```

layoutRipple = (LayoutRipple) itemView.findViewById(R.id.itemButtons);
                 setOriginRiple(layoutRipple);

```
    holder.layoutRipple.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View arg0) {
                    if (viewclickevent!=null) {
                        viewclickevent.OnViewItemClick(position);
                    }
                }
            });
```

**Comment by navasmdc** [comment]
Hi, download the last version of the library, I've tried the LayoutRipple view in a ListView and it work very well
