### ISSUE TITLE
onCheckedChangeListener

### ISSUE THREAD

**Issue by dallinski** [navasmdc/MaterialDesignLibrary#148]
Could we please get an onCheckedChangeListener? Thanks for the great library!

**Comment by xcelder** [comment]
you already have the onCheckListerner(). For what exactly do you need another listener?

**Comment by dallinski** [comment]
I can't remember why any more (it's been over a year and a half since the request), but I thought it was because the listener wasn't being triggered when going from a checked to an unchecked state. Whether that is actually the case or not, I'm not sure. I don't need it any more, so I'll just close this issue.
