### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by hellworld** [navasmdc/MaterialDesignLibrary#155]
Android Studio 1.1 beta4:
Error:(97, 0) Cannot call getBootClasspath() before setTargetInfo() is called.

**Comment by miao1007** [comment]
Temporarily solved by deleting following code in 

MaterialDesignLibrary/MaterialDesign/build.gradle

```
task sourcesJar(type: Jar) {
    from android.sourceSets.main.java.srcDirs
    classifier = 'sources'
}

task javadoc(type: Javadoc) {
    source = android.sourceSets.main.java.srcDirs
    classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
}

task javadocJar(type: Jar, dependsOn: javadoc) {
    classifier = 'javadoc'
    from javadoc.destinationDir
}

artifacts {
    archives javadocJar
    archives sourcesJar
}

task findConventions << {
    println project.getConvention()
}
```

**Comment by juanpalazuelos** [comment]
I had the same issue, I solved it by modifying my project's build.gradle file

From 
classpath 'com.android.tools.build:gradle:1.1.0'

To
classpath 'com.android.tools.build:gradle:1.1.1'

I hope it helps you
