### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by weejim76** [navasmdc/MaterialDesignLibrary#160]
Hi,

I am using the following xml in my NavigationDrawer and am getting a NullPointerException when the button is clicked. The exception only happens when materialdesign:animate="true" and goes away when materialdesign:animate="false"

```
    <com.gc.materialdesign.views.ButtonFloatSmall
        android:id="@+id/add_tab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentRight="true"
        android:layout_marginTop="10dp"
        android:layout_marginRight="@dimen/edge_margin"
        android:background="#1E88E5"
        materialdesign:animate="true"
        materialdesign:iconDrawable="@drawable/ic_action_new" />
```

Stack trace:

02-16 22:41:34.029: D/AndroidRuntime(4584): Shutting down VM
02-16 22:41:34.029: W/dalvikvm(4584): threadid=1: thread exiting with uncaught exception (group=0x4161c8b0)
02-16 22:41:34.039: E/AndroidRuntime(4584): FATAL EXCEPTION: main
02-16 22:41:34.039: E/AndroidRuntime(4584): java.lang.NullPointerException
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3055)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.View.getDisplayList(View.java:12957)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.View.getDisplayList(View.java:13062)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3060)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.View.getDisplayList(View.java:12957)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.View.getDisplayList(View.java:13062)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3060)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.View.getDisplayList(View.java:12957)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.View.getDisplayList(View.java:13062)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3060)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.View.getDisplayList(View.java:12957)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.View.getDisplayList(View.java:13062)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3060)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.View.getDisplayList(View.java:12957)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.View.getDisplayList(View.java:13062)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1411)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1359)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.ViewRootImpl.draw(ViewRootImpl.java:2377)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2249)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1882)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1009)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5508)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.Choreographer.doCallbacks(Choreographer.java:562)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.Choreographer.doFrame(Choreographer.java:532)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.os.Handler.handleCallback(Handler.java:730)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.os.Handler.dispatchMessage(Handler.java:92)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.os.Looper.loop(Looper.java:213)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at android.app.ActivityThread.main(ActivityThread.java:5225)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at java.lang.reflect.Method.invokeNative(Native Method)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at java.lang.reflect.Method.invoke(Method.java:525)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
02-16 22:41:34.039: E/AndroidRuntime(4584):     at dalvik.system.NativeStart.main(Native Method)

**Comment by larrytech7** [comment]
i have this same issue but in my case, this happens only when the button is clicked in the first item of my adapter. It does not happen when the button is clicked on every other item of the list
