### ISSUE TITLE
How to fix the problem "Attribute "rippleColor" has already been defined" ?

### ISSUE THREAD

**Issue by willowcheng** [navasmdc/MaterialDesignLibrary#167]
Hi,

I face the trouble with `Error:(1) Attribute "rippleColor" has already been defined` since I also use [MaterialNavigationDrawer](https://github.com/neokree/MaterialNavigationDrawer) library. 

It seems there is confict with these two repositories in terms of some defined attributes.

**Comment by technohowl** [comment]
Yes, same issue. Eventually I had to remove this library from the project.

**Comment by tatianagrange** [comment]
Hi,

I have the same problem. Someone know if it come from update on MaterialNavigationDrawer or MaterialDesignLibrary?

**Comment by willowcheng** [comment]
@tatianagrange , I've reported the same problem to MaterialNavigationDrawer. You now could update your MaterialNavigationDrawer to version 1.3.2 to solve this problem.

`compile 'it.neokree:MaterialNavigationDrawer:1.3.2'`

Iit's fine for me.

**Comment by tatianagrange** [comment]
@willowcheng : Thank's a lot! Problem solve!

**Comment by technohowl** [comment]
Thanks. I think you should mark the issue as closed.

**Comment by wilksmatt** [comment]
Hi, the same error occurs because of a conflict with 'com.android.support:design:22.2.0'. Can the "rippleColor" attribute be corrected in MaterialDesignLibrary? Thanks.

**Comment by chrisdonovan1006** [comment]
Hey, I am having the same issue as wilksmatt can the MaterialDesignLibrary be updated, cheers.

**Comment by ArunPandiyan** [comment]
Still there is problem because of "rippleColor".

**Comment by wilksmatt** [comment]
Hi,

Can this issue be re-opened? I expect that the fix is pretty straight forward. I would love to use this library in my app in the Google Play store but currently cannot because of this issue.

Thanks,

Matt

**Comment by growingdever** [comment]
I met same problem. It should be changed.

**Comment by Informatheus** [comment]
Same problem, i had to stop using this lib cause i need com.android.support:design:22.2.1.

**Comment by growingdever** [comment]
Me too. I think this library should add prefix for variables of resources to avoid these errors.

**Comment by HectorFGarcia** [comment]
I have the same problem, I'm using com.android.support:design:23.0.0.

**Comment by sohayb** [comment]
This has been reported multiple times. What I think as a solution if someone really needs the library, is to fork and change the attributes (add a prefix) or download it, add a prefix to the attributes and use it inside his app module.

**Comment by kwiknikk** [comment]
@sohayb Thanks! I was able to download the code, find the attributes.xml file and just rename the rippleColor and it works!

**Comment by Zane-cqupt** [comment]
@willowcheng I use the design 23.0.1, then I change the matrialNavigationDrawer version to 1.3.2. It doesn't work for me

**Comment by willowcheng** [comment]
@Zane-cqupt Hi, sorry I didn't use design library yet. I'm not sure which MaterialNavigationDrawer library you are using but I moved to koesie10's [MaterialNavigationDrawer](https://github.com/koesie10/MaterialNavigationDrawer) library since original author doesn't support the library any more (some bugs are not fixed yet).

**Comment by Zane-cqupt** [comment]
@willowcheng hi，are u chinese?你好。you mean the original auther of MatrialNavigationDrawer library doesn't support the library anymore?..fine, I remove the design library. and if I must use the Drawer in android, I can use the DrawerLayout in design library instead of MatrialNavigationDrawer library.

**Comment by willowcheng** [comment]
@Zane-cqupt 嗯，是的。MaterialNavigationDrawer 这个库很方便使用倒是。

**Comment by ImTosS** [comment]
I´m having the same issue right now, I´ll have to remove the library from my project.

**Comment by niwinnm** [comment]
I have modified the attribute "rippleColor" to "mRippleColor". Have forked the library in here: [https://github.com/vajro/MaterialDesignLibrary](https://github.com/vajro/MaterialDesignLibrary). Hope it helps someone.
