### ISSUE TITLE
FloatButton in RTL

### ISSUE THREAD

**Issue by sohayb** [navasmdc/MaterialDesignLibrary#174]
Hello,
the FloatButton in RTL setting is filling the whole width when having width as wrap_content. I fixed it by setting a fixed width.
Is there any other solution for that?

Thank you

**Comment by muhammad-naderi** [comment]
same problem here, 
not a problem in 4.2.2
but it's behaving as you said in 4.4.2, 5.0.1, 5.1

thanks for workaround, btw!
