### ISSUE TITLE
How can I run this demo in Android Studio?

### ISSUE THREAD

**Issue by zhenbeiju** [navasmdc/MaterialDesignLibrary#176]
I import this project to Android Studio, It builds done,But no Run actions  default, I don't know how to add a Run action, can any one help me  ?

**Comment by imcc** [comment]
在`setting.gradle`里把`MaterialDesignDemo`包括进去就好了~  
像下面这样
```java
include ':MaterialDesign',':MaterialDesignDemo'
```

**Comment by zhenbeiju** [comment]
谢谢，，
