### ISSUE TITLE
Button in Fragment

### ISSUE THREAD

**Issue by Spirit81** [navasmdc/MaterialDesignLibrary#177]
I am trying to use button in Fragment, but it allways look for onClick or method in mainActivity
How to look for method inside the Fragment where button is placed?

thx

**Comment by mehrad-rafigh** [comment]
That's strange! Could you please paste your code?

**Comment by Spirit81** [comment]
in layout I put android:onClick="btnClick"

and place 
public void btnClick(View v){
      Toas.makeTxt....bla bla
}

it works if btnClick is in MainActivity, if it is in fragment does not work

**Comment by mehrad-rafigh** [comment]
Well thats strange. I use the buttons with onclicklisteners in the fragment. 

See the following gist:
https://gist.github.com/mehrad-rafigh/36edf12e3a9dee17827a
