### ISSUE TITLE
Is there a way to set the circle colors in xml for ProgressBarCircularIndeterminate??

### ISSUE THREAD

**Issue by enginebai** [navasmdc/MaterialDesignLibrary#183]
I know there is `android:background="@color/main"` to set the circle color for `ProgressBarCircularIndeterminate`. But I'd like to add more colors for it **in xml** rather than by programming. Is there any way to achieve it??

Thanks.

**Comment by xcelder** [comment]
I don't understan your issue very well, you can use the method setBackgroundColor for change it programmatically.

**Comment by enginebai** [comment]
Never mind, thanks for your help.
