### ISSUE TITLE
Remove ic_launcher.png

### ISSUE THREAD

**Issue by osrl** [navasmdc/MaterialDesignLibrary#184]
Could you remove unused ic_launcher.png?

**Comment by navasmdc** [comment]
ok I'll remove it in the next version

**Comment by osrl** [comment]
Thank you

**Comment by npike** [comment]
When do you plan on releasing a new version of the library that doesn't have ic_launcher?

**Comment by Retistic** [comment]
@navasmdc Could you release a new version without the launcher as it's requiring workarounds with gradle?

**Comment by zhenbeiju** [comment]
hello, any new version?
