### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by chintanshah24** [navasmdc/MaterialDesignLibrary#190]
I got this error on using the Float Action Button
java.lang.NoClassDefFoundError: com.nineoldandroids.view.ViewHelper
            at com.gc.materialdesign.views.ButtonFloat$1.run(ButtonFloat.java:108)

**Comment by chintanshah24** [comment]
Importing nineOldAndroid makes the app function but that shouldn't happen

**Comment by francisbrito** [comment]
Ran into this a moment ago. Importing [NineOldAndroids](http://mvnrepository.com/artifact/com.nineoldandroids/library/2.4.0) Fixed it for me too. Maybe documentation is outdated...

**Comment by raghuveer-s** [comment]
I ran into this as well. Adding compile 'com.nineoldandroids:library:2.4.+' to the gradle file made it work.

**Comment by Grohden** [comment]
same error here, and thx @raghuveer-s , that line solved my problem :D

**Comment by TMSantos** [comment]
Just add:
compile 'com.nineoldandroids:library:2.4.+'
