### ISSUE TITLE
Can't set the text of buttons in dialog

### ISSUE THREAD

**Issue by SilleBille** [navasmdc/MaterialDesignLibrary#202]
Hi, I am using your library and my app depends a lot on it. I'm currently not able to set custom text on Accept and Cancel of dialog. I tried setting 

          ButtonFlat acceptButton = dialog.getButtonAccept();
          acceptButton.setText("Accept Me!");

I get the error: Attempt to invoke virtual method 'void com.gc.materialdesign.views.ButtonFlat.setText(java.lang.String)' on a null object reference

I followed your guide. Also, I followed on the same issue faced by another developer. Can you please help me solve this issue?

**Comment by MrMojo86** [comment]
I have the same problem...

**Comment by manishkungwani** [comment]
This will resolve the issue:

		dialog.addCancelButton(activity.getResources().getString(R.string.abort_dialog_cancel)); // Set the text for the cancel button, before the dialog is created.

		dialog.show(); // Access to accept button ButtonFlat acceptButton = dialog.getButtonAccept();
		acceptButton.setText(activity.getResources().getString(R.string.abort_dialog_ok)); // Access to cancel button
		ButtonFlat cancelButton = dialog.getButtonCancel();
		cancelButton.setText(activity.getResources().getString(R.string.abort_dialog_cancel));

**Comment by manishkungwani** [comment]
@SilleBille are you still seeing that issue?

**Comment by josinaldobarbosa** [comment]
Try this: dialog.getButtonAccept().setText("Accept Me!");

**Comment by SilleBille** [comment]
Thank you so much. That helped me a lot :)

**Comment by TusharPatilGithub** [comment]
Create ButtonFlat object below the dialog.show.
it work's - 

dialog.setOnCancelButtonClickListener(new View.OnClickListener() {

 @Override
 public void onClick(View v) {
 dialog.dismiss();
 ((Activity) context).finish();
 }
 });
 dialog.show();
 ButtonFlat acceptButton = dialog.getButtonAccept();
 acceptButton.setText("OK");
 dialog.setOnAcceptButtonClickListener(new View.OnClickListener() {

 @Override
 public void onClick(View v) {
 dialog.dismiss();
 }
 });
 dialog.setOnCancelButtonClickListener(new View.OnClickListener() {

 @Override
 public void onClick(View v) {
 dialog.dismiss();
 }
 });
 dialog.show();
 ButtonFlat acceptButton = dialog.getButtonAccept();
 acceptButton.setText("OK");
