### ISSUE TITLE
Button Rectangle takes long time

### ISSUE THREAD

**Issue by SilleBille** [navasmdc/MaterialDesignLibrary#208]
I usually use linearlayout with weight to place my View Elements. Everything is fine except the Button Rectangle. It takes long time to respond i.e. till the ripple effect fills the button my action is not triggered. Is there anyway to speed up the animation or trigger the action quickly?

**Comment by xyiyox** [comment]
I agree with you, the animation of Button Rectangle takes a long time and I want reduce that time, if somebody knows how do that please share with us =)

**Comment by SilleBille** [comment]
Hi @xyiyox

I overcame the issue by setting the ripple speed in java. Use setRippleSpeed property and set to your required value :)

**Comment by xyiyox** [comment]
Thank you ! It works fine
