### ISSUE TITLE
Bug: Checkbox doesn't work fine on WXGA800(1920x1080) phone

### ISSUE THREAD

**Issue by androchentw** [navasmdc/MaterialDesignLibrary#217]
The Checkbox view got some strange animation of particular resolution - WXGA800(1920x1080).
It will happen 2 effect:
1. Jumping animation during check (after you click the unchecked Checkbox)
2. The Check sign is not at the center of the box, or even out of the box, while the background is changed to blue

Sorry I don't know how to record the animation, but you should be able to re-create the condition by the AVD setting as below.
![screen shot 2015-04-01 at 6 32 10 pm](https://cloud.githubusercontent.com/assets/2317501/6939401/fc402428-d89e-11e4-89d2-413edd00c9f5.png)

**Comment by bondiep** [comment]
when I use checkbox in xml, if I have an attribute (materialdesign:check="true"). Error occur :(
2015-04-06 04:41:12 - Scanner360
[2015-04-06 04:41:12 - Scanner360] /Volumes/Untitled 3/workspace/Scanner360/res/layout/activity_settings.xml:70: error: Error parsing XML: unbound prefix

When I delete it, When running, it throws an exception

java.lang.RuntimeException: Unable to start activity ComponentInfo{...SettingsActivity}: android.view.InflateException: Binary XML file line #70: Error inflating class com.gc.materialdesign.views.CheckBox

My xml : android:id="@+id/checkbox_auto_protection"
android:layout_width="wrap_content"
android:layout_height="wrap_content"
android:layout_alignParentRight="true"
android:layout_centerVertical="true"
android:background="#1E88E5" />

Please help me !

**Comment by Pantsu-It** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
