### ISSUE TITLE
Is this library maintained any longer?

### ISSUE THREAD

**Issue by inteist** [navasmdc/MaterialDesignLibrary#222]
Wondering if this library is actively maintained any longer. There are many unanswered pull requests as well as issues.

**Comment by ppamorim** [comment]
+1

**Comment by jmvines** [comment]
+1

**Comment by adamski8** [comment]
+1

**Comment by mehrad-rafigh** [comment]
I posted a few issues a while ago and they haven't been fixed yet. I switched to this library:
https://github.com/rey5137/material

**Comment by inteist** [comment]
@mehrad-rafigh I checked out this library and while looking quite promising it has unfortunately many bugs and inconsistencies. I could not get the progress indicator to work. The date picker was broken then the dev fixed it and broke it again and fixed it. The most alarming thing to me was that the picker was actually broken in L where (I think) it should have been using the original (system picker). Just glance over some of the issues.
There are a few pretty good L libraries but unfortunately not quite anyone of them is good and stable enough. I wish all these devs developing all these disparaate libs could join forces and we could finally have a polished library.

**Comment by ppamorim** [comment]
@inteist  +1 for you.
I'm abandoned this library.

**Comment by inteist** [comment]
@ppamorim did you mean the Rey Pham's library? https://github.com/rey5137/material ? 
I was commenting on Rey's library --> https://github.com/rey5137/material

I did not try this repo's library as I did not even want to try something that is not maintained.

If you did mean Rey's library. What are you using instead? 

I am using 

com.pnikosis:materialish-progress    for progress indicator and
I am using the version 1.1 of Rey's library for date picker but only because I don't see anything better.

I think Rey's library is very nicely done. I provided the dev. some feedback which he even implemented I saw but when I had problem with the progress dialog he did not get back to me after the supposed fix that had to fix the issue but was not working for me still.

**Comment by ppamorim** [comment]
@inteist I use the Rey library too.

**Comment by shkschneider** [comment]
+1

**Comment by navasmdc** [comment]
Hi sorry but I'd had a lot of work in my job, but I come back! And I'm trying fix the bugs! I upload a new version today!

**Comment by sohayb** [comment]
Welcome back @navasmdc :)
