### ISSUE TITLE
Float Button not showing

### ISSUE THREAD

**Issue by Thames1990** [navasmdc/MaterialDesignLibrary#237]
I implemented the FAB as shown in my layout XML and tried to create it in my code. But the FAB isn't showing.

This is my code:
ButtonFloat buttonFloat = (ButtonFloat) getActivity().findViewById(R.id.buttonFloat);
buttonFloat.show();

**Comment by navasmdc** [comment]
Sorry but you've to implement the FloatButton in the xml file, the show function animate the FloatButton from the bottom of the screen.
