### ISSUE TITLE
Auto hide FloatButton as you scroll a ListView down

### ISSUE THREAD

**Issue by 2hamed** [navasmdc/MaterialDesignLibrary#241]
Hi there,
Is it possible to make the FloatButton auto hide as you scroll a ListView down and then reappear upon scrolling up?

**Comment by 2hamed** [comment]
Here is the [pull request](https://github.com/navasmdc/MaterialDesignLibrary/pull/242) I made to address this feature.

**Comment by navasmdc** [comment]
Thx! I've pulled your request!
