### ISSUE TITLE
Not able to chaneg the color of the button

### ISSUE THREAD

**Issue by onlyrohits** [navasmdc/MaterialDesignLibrary#258]
Tried changing the color to "#b71c1c" with  android:background="#b71c1c" but it sticks to default blue color.

My dependency is compile 'com.github.navasmdc:MaterialDesign:1.+@aar'

and the Button XML:

<com.gc.materialdesign.views.ButtonFloat
                android:id="@+id/buttonFloat"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentRight="true"
                android:layout_alignParentBottom="true"
                android:layout_marginRight="24dp"
                android:background="#b71c1c"
                materialdesign:animate="true"
                materialdesign:iconDrawable="@drawable/ic_action_new"
                />

**Comment by vipinshukla83** [comment]
same here ,

**Comment by issyzac** [comment]
same same...

**Comment by ppamorim** [comment]
This library was abandoned. Use the library rey5137 - Material.

**Comment by navasmdc** [comment]
Hi sorry i've had a lot of work, it is fixed in the last version!
