### ISSUE TITLE
Changing the Typeface to the buttons. 

### ISSUE THREAD

**Issue by EugeneHoran** [navasmdc/MaterialDesignLibrary#27]
Suggest allowing users to change the typeface to custom fonts for the buttons.  The current text is quite large and wont match most application fonts.  Great library and look forward to updates!!

**Comment by kmuralidharan91** [comment]
@eugeneisrambo : can you show the way you assigned typeface to font ??
it will be much helpfull if you share it with as.

**Comment by eugeneisrambo** [comment]
@kmuralidharan91  I did it a while back and this is how I achieved this.  If it doesn't work let me know and I will have a look at the code.  

        Typeface robot_regular = Typeface.createFromAsset(getAssets(), "fonts/Roboto-Regular.ttf");
        ButtonFlat btnFlat = (ButtonFlat) findViewById(R.id.btnFlat);
        btnFlat.getTextView().setTypeface(robot_regular);

**Comment by gowravshekar** [comment]
```java
public class Button extends ButtonRectangle {

    public Button(Context context, AttributeSet attrs) {
        super(context, attrs);
        TextView textView = this.getTextView();
        if (textView != null) {
            Typeface customTypeface = Typeface.createFromAsset(context.getAssets(), "fonts/Ubuntu-B.ttf");
            textView.setTypeface(customTypeface);
        }
    }
}
```

Extending the class and setting customTypeface is not working. `this.getTextView()` always returns `null`. How to set the custom font for all the buttons in the app without calling the function every time as mentioned in above solution?
