### ISSUE TITLE
Add prefix to custom attributes

### ISSUE THREAD

**Issue by sohayb** [navasmdc/MaterialDesignLibrary#277]
Hello,
Can you please add a prefix to your custom attributes so it can play nicely with other libraries such as the newly introduced Android Design Support Library?

**Comment by sohayb** [comment]
Same issue in #274

**Comment by niwinnm** [comment]
I have modified the attribute "rippleColor" to "mRippleColor" 

Have forked the current version in here: https://github.com/vajro/MaterialDesignLibrary
