### ISSUE TITLE
Error: Attribute "rippleColor" has already been defined

### ISSUE THREAD

**Issue by SharerMax** [navasmdc/MaterialDesignLibrary#279]
Attribute "rippleColor" has already been defined at Design Support Library('com.android.support:design:22.2.0').

**Comment by rimidalv** [comment]
I have same problem

**Comment by sohayb** [comment]
already referenced from issues #274 and #277

**Comment by Informatheus** [comment]
Same problem, i had to stop using this lib cause i need com.android.support:design:22.2.1.

**Comment by niwinnm** [comment]
I have modified the attribute "rippleColor" to "mRippleColor"

Have forked the current version in here: https://github.com/vajro/MaterialDesignLibrary

**Comment by Pantsu-It** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
