### ISSUE TITLE
Failed to resolve com.github.navasmdc:MaterialDesign:1.5

### ISSUE THREAD

**Issue by horaltirane** [navasmdc/MaterialDesignLibrary#288]
Hi,

Failed to resolve com.github.navasmdc:MaterialDesign:1.5

**Comment by defcon89** [comment]
+1

**Comment by norman-kapschefsky** [comment]
+1 since a few minutes

**Comment by cyklodev** [comment]
Same here both failed 
    compile 'com.github.navasmdc:MaterialDesign:1.+@aar'
    compile 'com.github.navasmdc:MaterialDesign:1.5@aar'

**Comment by dhavaln** [comment]
Same here, started happening today.

**Comment by dhavaln** [comment]
Works now for mw.

**Comment by norman-kapschefsky** [comment]
Still not working (1.+ and 1.5). @dhavaln have you done something special?

**Comment by dhavaln** [comment]
@norman-kapschefsky nothing particularly, i did clean & build again and the error is gone. 

Just to cross check, I just did another clean/build and it still works.

**Comment by horaltirane** [comment]
After quit, restart, clean and build.

Error:A problem occurred configuring project ':app'.
      > Could not GET 'https://jcenter.bintray.com/com/github/navasmdc/MaterialDesign/1.5/MaterialDesign-1.5.pom'.
         > peer not authenticated

**Comment by Inlacou** [comment]
Same here:

Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not resolve com.github.navasmdc:MaterialDesign:1.5.
     Required by:
         wikiopps:app:unspecified
      > Could not GET 'https://jcenter.bintray.com/com/github/navasmdc/MaterialDesign/1.5/MaterialDesign-1.5.pom'.
         > peer not authenticated
      > Could not GET 'https://jcenter.bintray.com/com/github/navasmdc/MaterialDesign/1.5/MaterialDesign-1.5.pom'.
         > peer not authenticated

Tried to clean and build, restarted Android Studio, nothing.

**Comment by cyklodev** [comment]
The whole MaterialDesign is missing in http://repo.jfrog.org/artifactory/libs-release-bintray/com/github/
:/

**Comment by Dallanosm** [comment]
I have the same problem.

**Comment by tuncaulubilge** [comment]
Add jcenter() to repositories if you don't have it already. It started working after a clean/rebuild

repositories {
    jcenter()
}

dependencies {
    compile 'com.github.navasmdc:MaterialDesign:1.5@aar'
}

**Comment by dhavaln** [comment]
If it helps, i am not using any specific repo for jcenter:

repositories {
    jcenter()
}

**Comment by norman-kapschefsky** [comment]
For me it works again. Did nothing. Just gradle sync. Hope you guys will get it back as well.

**Comment by horaltirane** [comment]
It work again. Just gradle sync????

**Comment by cyklodev** [comment]
Thanks for resolving this issue ! 
 It works fine now (just clean & build )

**Comment by TusharPatilGithub** [comment]
Thanks....
It Works for me.

**Comment by zjcoming** [comment]
+1.but how to solve this problem?
