### ISSUE TITLE
RectangleButton: Can't able to change the background colour to "White"

### ISSUE THREAD

**Issue by sincerekamal** [navasmdc/MaterialDesignLibrary#362]
Hi Guys,
  I can't able to change the `Rectangle` button colour to "white", if I set to white, it is showing in "Black" background with "White" text. How can I fix this ?

And also how can I change the Text colour of the button.

**Comment by tuxkids** [comment]
for change button color
you need to declare color as int

for example

`int GREEN = Color.parseColor("#60b044");`

then you can change color programmatically like this

`yourbutton.setBackgroundColor(GREEN);`
