### ISSUE TITLE
Interference with FAB of Android Support Design Library

### ISSUE THREAD

**Issue by abhinav-adtechs** [navasmdc/MaterialDesignLibrary#363]
Basically the attribute, **rippleColor** is already defined for the Floating Action bar of com.android.support:design:23.1.1. Thus, disallowing me to use both the libraries at the same time. Please refactor it.

> Error:(143) Attribute "rippleColor" has already been defined

**Comment by trolloks** [comment]
I forked and refactored the attribute name to rippleAnimationColor. I sent a pull request, so either you use my forked project for now or wait for the it to be merged to master.

**Comment by abhinav-adtechs** [comment]
Cool. :)
