### ISSUE TITLE
Error where variables are not public in com.gc.materialdesign.views.* and therefore cannot be accessed from outside the package

### ISSUE THREAD

**Issue by skibzy** [navasmdc/MaterialDesignLibrary#417]
Hi people, I am having an issue where classes in the view folder cannot access variables from the Material design because they are not public. The referenced values are in these 2 java files:

1. com.gc.materialdesign.views.CustomView
2. com.gc.materialdesign.views.Button

How can this be rectified? Any assistance will be greatly appreciated.

**Comment by bubba86** [comment]
[](url)
