### ISSUE TITLE
Changing ButtonFloat icon Pragmatically

### ISSUE THREAD

**Issue by EugeneHoran** [navasmdc/MaterialDesignLibrary#42]
Is it possible to change the ButtonFloat  Icon Pragmatically?  if so, can you share an example.  I have attempted but keep getting errors.  If not would you be able to implement it.  Cheers!

**Comment by RichardSilveira** [comment]
I am receiving the "cannot resolve method" message when trying to use the setDrawableIcon in an instance of com.gc.materialdesign.views.Button.

I´m compiling the packages
com.github.navasmdc:MaterialDesign:1.5@aar
 com.android.support:appcompat-v7:22.1.1
