### ISSUE TITLE
Type in your language with Gboard

### ISSUE THREAD

**Issue by ghost** [navasmdc/MaterialDesignLibrary#426]
I'm using Gboard to type in English (US) (QWERTY). You can try it at: https://gboard.app.goo.gl/FNxkG

**Comment by Pantsu-It** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Pantsu-It** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
