### ISSUE TITLE
Graphic problem

### ISSUE THREAD

**Issue by Anth06ny** [navasmdc/MaterialDesignLibrary#61]
They have a graphic problem if we slide out of a row in LayoutRipple

![screenshot_2014-12-04-17-28-33](https://cloud.githubusercontent.com/assets/6651017/5301691/144ad458-7bdb-11e4-8ba5-dd8c81e2f2f6.png)

The correction : 
In RippleView.java

 else if (event.getAction() == MotionEvent.ACTION_UP ) {
...
}

become

 else if (event.getAction() == MotionEvent.ACTION_UP || event.getAction() == MotionEvent.ACTION_CANCEL) {

}

**Comment by navasmdc** [comment]
Hi, good news, the bug is fixed in the last version!
