### ISSUE TITLE
Import project to Android Studio

### ISSUE THREAD

**Issue by WojciechCz** [navasmdc/MaterialDesignLibrary#63]
Good morning to You,

I cant import this project. I try everythink that i thought will work. Browse through stackoverflow, multiple google pages and still i am stuck.

Can anyone tell me how to import this lib to my project ?

I use Android Studio 1.0 RC 4.

**Comment by MelodyAustin** [comment]
I followed your instructions and got this error :(
Error:(2, 0) Plugin with id 'com.github.dcendents.android-maven' not found.
I am getting this error after importing it into android studio, how do I import it and not get this error..
I am new to developing for android,..Sorry if this is a bad question, but I am unable to get rid of this error :(

**Comment by Inoy1st** [comment]
@MelodyAustin 
there is nothing difficult in adding libs to MaterialDesign Library
put this in top of Library's build.gradle

    buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.github.dcendents:android-maven-plugin:1.2'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.0'
    }
    }
    apply plugin: 'com.android.library'

Next time, just Google plugin ID

The real fun comes after - I'm getting "Failed to Inflate" error on app start.

**Comment by MelodyAustin** [comment]
@Inoy1st thank you for the reply! But now it says

**Comment by Inoy1st** [comment]
@MelodyAustin 
Try to Google: *Gradle DSL method not found: 'bintray()'*
Find results from *stackoverflow.com*

I've already had similar error, don't remember how I fixed it.

**Comment by MelodyAustin** [comment]
Thank you! It just worked or restarting android studio :)

**Comment by msysmilu** [comment]
It might have worked for other and I'm really keen on that. But, step 2) from above "copy MaterialDesign folder which contains the lib to your project root or some where in your project folder" is a bit confusing.

**Comment by NhocKun** [comment]
tks alot. It work perfect!
