### ISSUE TITLE
Wish can use with gradle

### ISSUE THREAD

**Issue by stormzhang** [navasmdc/MaterialDesignLibrary#69]
Why not upload the library to maven, so we can use with gradle

**Comment by supershuai** [comment]
+1

**Comment by pkliang** [comment]
+1

**Comment by Kuratkoo** [comment]
@navasmdc any progress?

**Comment by navasmdc** [comment]
Hi guys, GOOD NEWS!!, I've finally gotten it, I've upload the project to the Jcenter if you want acces to the library, have to add these lines in your buil.gradle

repositories {
    jcenter()
}

dependencies {
    compile(group: 'com.github.navasmdc', name: 'MaterialDesign', version: '1.0', ext: 'aar')
}

**Comment by rulogarcillan** [comment]
Thanksssss

**Comment by pankajbatra** [comment]
@navasmdc Thanks a lot!

**Comment by www40** [comment]
thanks
