### ISSUE TITLE
Is there a way to make a progress dialog?

### ISSUE THREAD

**Issue by jasper-lu** [navasmdc/MaterialDesignLibrary#79]
I.e. put a circular progress inside a dialog

**Comment by navasmdc** [comment]
Add it!
You can use:
>```java
>ProgressDialog progressDialog = new ProgressDialog(Context context,String title);
>```
Or:
>```java
>ProgressDialog progressDialog = new ProgressDialog(Context context,String title, int progressColor);
>```
