### ISSUE TITLE
MaterialDesignLibrary vs Android Support Library (appcompat 7 v21) ?

### ISSUE THREAD

**Issue by ramswaroop** [navasmdc/MaterialDesignLibrary#89]
I am a greenhorn in material design stuff, so can you tell me whether these components are there in appcompat or not? 

If I really need to use this library then whats the purpose of appcompat library?

*NOTE: My app supports API Level 10+.*

**Comment by navasmdc** [comment]
This library have more components that Appcompact 7 v21 and it is most customizable
