### ISSUE TITLE
ButtonRectangle OnClickListener not triggered until ripple effect finishes

### ISSUE THREAD

**Issue by guilhermearaujo** [navasmdc/MaterialDesignLibrary#94]
When you tap a ButtonRectangle, its OnClickListener method will not be triggered until the ripple effect animation has finished.

I am not fully sure this is the desired behavior, but in my case I am performing some async tasks when the button is pushed, so it would be a lot better if the task could start immediately. For instance, I'd also like to right away replace the button text with "Loading...", but this will take effect only after the animation is done.

I haven't tested with the other buttons, but since they all extend `Button`, I suppose they all act the same way.

**Comment by squeeish** [comment]
Yes I've noticed the same thing too. Furthermore, the animation is extremely slow. 

I would love to use this library as it has almost everything I need but the button behaviour is a real killer! :)

**Comment by navasmdc** [comment]
Fix it!
By Default the OnclickListener executes after of the ripple effect but  if you want that the action executes before of the ripple effect, you have to put in the attributes materialdesign:clickAfterRipple = "true"

**Comment by squeeish** [comment]
Thanks navasmdc, but it doesn't seem to be working (tested on both ButtonRectangle and ButtonFlat). Does it work for you @guilhermearaujo ?

**Comment by drinfernoo** [comment]
Neither materialdesign:clickAfterRipple="true" or "false" works for me.

**Comment by mynavy** [comment]
Just change the speed of the ripple so it will trigger faster.

mButtonRectangle.setRippleSpeed(120)
