### ISSUE TITLE
Dialog cancel button callback is wrong

### ISSUE THREAD

**Issue by dadino** [navasmdc/MaterialDesignLibrary#95]
https://github.com/navasmdc/MaterialDesignLibrary/blob/master/MaterialDesign/src/com/gc/materialdesign/widgets/Dialog.java

Line 186, onAcceptButtonClickListener instead of onCancelButtonClickListener.

**Comment by navasmdc** [comment]
Thanks, I fixed it, its available in the next version

**Comment by dadino** [comment]
When will it be available?

**Comment by navasmdc** [comment]
It already is available!!
