### ISSUE TITLE
How to change the text of buttons in dialog

### ISSUE THREAD

**Issue by mehrad-rafigh** [navasmdc/MaterialDesignLibrary#96]
Hi there,

I want to change the text of the buttons in the dialog but can't find an easy way to do that. Do I really need to create two ButtonFlat Objects for that or is there an easier way to achieve what I want to do?

**Comment by navasmdc** [comment]
Hi,

if you want change the text of the buttons, the dialog have getButtonAccept() and getButtonCancel(); functions that return a ButtonFloat and with this buttonfloat you can setText to set your text

**Comment by mehrad-rafigh** [comment]
Thanks. I will give it a try

**Comment by mehrad-rafigh** [comment]
This is what I get when I call the getButtonAccept() and getButtonCancel() and want to set the text with .setText()

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.gc.materialdesign.views.ButtonFlat.setText(java.lang.String)' on a null object reference

**Comment by Macroyep** [comment]
I try change the text of the buttons ,but  getButtonAccept() and getButtonCancel() are null!

**Comment by mehrad-rafigh** [comment]
So two developers facing the same issue! This should issue should be opened again and most important fixed!

**Comment by Macroyep** [comment]
Thanks!

**Comment by GillesC** [comment]
I have the same problem. Both of the getters return null.

**Comment by Macroyep** [comment]
get the return after showing it

**Comment by Macroyep** [comment]
显示了窗口再通过geter来获取button

**Comment by MrMojo86** [comment]
I get the same error even if I use this code:

       ` dialog.show();
        // Access to accept button
        ButtonFlat acceptButton = dialog.getButtonAccept();
        acceptButton.setText(activity.getResources().getString(R.string.abort_dialog_ok));
        // Access to cancel button
        ButtonFlat cancelButton = dialog.getButtonCancel();
        cancelButton.setText(activity.getResources().getString(R.string.abort_dialog_cancel));`

**Comment by sphairo** [comment]
This code return null on cancellButton:   
dialog.show();
    // Access to accept button
    ButtonFlat acceptButton = dialog.getButtonAccept();
    acceptButton.setText(activity.getResources().getString(R.string.abort_dialog_ok));
    // Access to cancel button
    ButtonFlat cancelButton = dialog.getButtonCancel();
    cancelButton.setText(activity.getResources().getString(R.string.abort_dialog_cancel));`

**Comment by tbrand** [comment]
I was facing the same issue.
I found that you should call Dialog.addCancelButton(String) before calling Dialog.show();

Best.

**Comment by sunsongwen123** [comment]
dialog.addCancelButton("cancel");
